# config/meta.yml

meta_product_name: "SOS Donations"
meta_title: "SOS Donations - Building a better world"
meta_description: "Donations Plataform where Donors can review Campaigns Accontabilities in order to build Institutions Reputation!"
meta_image: "hands-together-og.jpg" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards
